name: webview_cookie_manager_example
description: Demonstrates how to use the webview_cookie_manager plugin.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.3

  webview_cookie_manager:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true