name: webview_cookie_manager_plus
description: "Have you been turned into a cookie management problem? This package can help. It has all of the cookie management functionality you have been looking for. This is a fork from webview_cookie_manager since this package has no maintenance."
version: 2.0.8
repository: https://github.com/webuijorgeGL/webview_cookie_manager_plus.git
homepage: https://github.com/webuijorgeGL/webview_cookie_manager_plus.git
issue_tracker: https://github.com/webuijorgeGL/webview_cookie_manager_plus/issues

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.webview_cookie_manager
        pluginClass: WebviewCookieManagerPlugin
      ios:
        pluginClass: WebviewCookieManagerPlugin
