name: webview_cookie_manager_plus
description: "Fork of webview_cookie_manager with full cookie management support. Helps handle cookies in WebView efficiently. Maintained and updated for better compatibility."
version: 2.0.12
repository: https://github.com/webuijorgeGL/webview_cookie_manager_plus.git
homepage: https://github.com/webuijorgeGL/webview_cookie_manager_plus.git
issue_tracker: https://github.com/webuijorgeGL/webview_cookie_manager_plus/issues

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.webview_cookie_manager
        pluginClass: WebviewCookieManagerPlugin
      ios:
        pluginClass: WebviewCookieManagerPlugin
